hdl4fpga/hdl4fpga

ULX3S/diamond/files.mk, library/scope/scopeio.vhd, library/scope/scopeio_pointer.vhd, library/video/video.vhd
=> fixing small syntax errors and forgotten lines

ULX3S/common/clk_25_200_40_66_25.v, ULX3S/diamond/makefile-800x600.diamond, ULX3S/scopeio/scopeio.vhd, library/ps2mouse/mousem.vhd
I shortly tested with DC step from the buttons
and the traces look good to me
=> ULX3S now uses input_ena

ULX3S/scopeio/scopeio.vhd, library/scope/scopeio_mouse2rgtr.vhd, library/scope/scopeio_ps2mouse2daisy.vhd
Tested for 1-5 inputs at ULX3S.
=> Unhardcoding mouse GUI for different numbers of inputs and color bits.

ULX3S/common/hdl/adc/max1112x_reader.vhd, ULX3S/scopeio/scopeio.vhd
I had fmax problems on some ULX3S boards with old ADC
and this new one seems to fix it. Old issues like trigger remain.
=> ULX3S: ADC shifting stage replaced with addressed write to improve fmax.

ULX3S/common/clk_25_500_100_62_25.v, ULX3S/common/clk_25_541_108_67_25.v, ULX3S/diamond/files.mk, ULX3S/diamond/makefile-1280x1024.diamond, ULX3S/diamond/ulx3s_12f_scope.ldf, ULX3S/scopeio/scopeio.vhd, library/scope/scopeio_mouse2rgtr.vhd, library/scope/scopeiopkg.vhd
After latest video rework, it synthesizes better on ULX3S
=> ULX3S: changes to let it compile after latest video rework

ULX3S/diamond/README.md
Readme is refreshed to match recent updates
=> ULX3S readme update

library/scope/scopeio_segment.vhd, library/scope/scopeiopkg.vhd, nexys2/ise/scopeio/scopio.xise, nexys2/scopeio/scopeio.vhd, s3estarter/scope/scopeio.vhd, s3starter/scopeio/scopeio.vhd
Minor improvements on style values for 600p and 1080p
=> Minor improvements on style values for 600p and 1080p

ULX3S/scopeio/scopeio.vhd, library/scope/scopeio_mouse2rgtr.vhd
after mouse wheel rotation selects new input channel,
also switch to the scale that belongs to the new channel
=> mouse2rgtr: better hack to update vertical scale after changing channel

library/scope/scopeio.vhd, library/scope/scopeio_axis.vhd, nexys2/ise/scopeio/scopio.xise, nexys2/scopeio/scopeio.vhd, nuhs3adsp/scope/scopeio.ucf
=> Fix layout bugs and scale numbers but still a glitch on numbers

library/common/std.vhd, library/scope/scopeio.vhd, library/scope/scopeio_amp.vhd, library/scope/scopeio_downsampler.vhd, library/scope/scopeio_pointer.vhd, library/scope/scopeio_rgtr.vhd, library/video/videopkg.vhd, nuhs3adsp/ise/scopeio/scopeio.xise, nuhs3adsp/scope/scopeio.vhd, s3starter/scopeio/scopeio.vhd, tools/scope/scope.js
Enable vertical and horizontal scale 
It might be some glitches.
Keep on eye on it
=> Enable vertical and horizontal scale 

library/scope/scopeio.vhd, library/scope/scopeio_amp.vhd, library/scope/scopeio_rgtr.vhd, library/scope/scopeiopkg.vhd, nuhs3adsp/ise/scopeio/scopeio.xise, s3starter/ise/scopeio/scopeio.xise
Move control-register description into scopeiopkg.
Fix scopeio_amp multiplier bug.
=> Move control-register description into scopeiopkg and fix amp multiplier

library/scope/scopeio_mouse2rgtr.vhd
To be more clean I tried to construct a function
that would generate rgtr bitfields from *_bf array
and required input values, but I was stuck in vhdl errors
so I opted for std_logic_vector concatenation with "&"
my code now can adapt if each bitfield changes length
but if order of bitfields change, then my could would not work
(but also no vhdl error will be issued which would make it
difficult to find what's wrong)
=> mouse2rgtr: unhardcoding rgtr bitfields

ULX3S/diamond/README.md, ULX3S/diamond/makefile, ULX3S/diamond/ulx3s_12f_scope.ldf, ULX3S/scopeio/scopeio.vhd, library/scope/scopeio_mouse2rgtr.vhd
A range function introduced to make mouse2rgtr adaptable to the changes of the fields order.
=> mouse2rgtr: unhardcoding with range function

library/scope/scopeio.vhd, library/scope/scopeio_axis.vhd, library/scope/scopeio_segment.vhd, library/scope/scopeio_tracer.vhd, s3starter/scopeio/scopeio.vhd
=> Fix hardcode grid height

library/scope/scopeio.vhd, library/scope/scopeio_axis.vhd, library/scope/scopeio_grid.vhd, library/scope/scopeio_segment.vhd, library/scope/scopeiopkg.vhd
=> grid and vertical scale can be scaled, still buggy

ecp3versa/scope/scopeio.vhd, library/scope/scopeio_axis.vhd, library/scope/scopeio_segment.vhd, library/scope/scopeiopkg.vhd, nexys2/common/nexys2.vhd, s3starter/common/s3starter.vhd, s3starter/scopeio/scopeio.vhd
Still others bugs to be fixed
Future 8 pixel division and 4x4 fonts for really small displays
=> Fix vertical scale bug

ULX3S/scopeio/scopeio.vhd, library/scope/scopeio_mouse2rgtr.vhd, library/scope/scopeiopkg.vhd
GUI channel select window has changed - it's no longer text box,
it's now tiny color box at lower left corner of the screen,
below vtaxis and left of hzaxis.
=> New 800x600 modes for full screen 4-segments and OLED screen test 1-segment

library/scope/scopeio.vhd
when there's no trigger, auto trigger is now much faster
and responsive to abrupt signal changes, more like analog scope
does it
=> scopeio: auto trigger fixed to provide fast response to signal changes

library/scope/scopeio.vhd, library/scope/scopeio_segment.vhd, library/scope/scopeiopkg.vhd, s3starter/scopeio/scopeio.vhd
16 and 8 pixels have been add to division_size.
Tyny fonts 4x4 have been.
=> Added axis_fontsize to display_layout

library/scope/scopeio.vhd
new (experimental) trigger can be optionally compiled with if/generate
New trigger didn't perform well for signal in MHz range (dotted lines)
but works slightly "better" for signal in kHz range (faster response
less discontinuity at T=0)
Something else should be done about the trigger to improve it for
all signal speeds.
=> scopeio: old trigger reverted, compiles by default.

ULX3S/common/hdl/oled/vga/oled_vga.vhd, ULX3S/common/hdl/oled/vga/oled_vga_init_pack.vhd, ULX3S/diamond/files.mk, ULX3S/diamond/ulx3s_12f_scope.ldf, ULX3S/scopeio/scopeio.vhd, library/scope/scopeio_mouse2rgtr.vhd, library/scope/scopeiopkg.vhd, library/video/videopkg.vhd
trying to fix ISE compilation errors
=> mouse2rgtr: changing integer/natural types in function F_bitfield

library/scope/scopeio_mouse2rgtr.vhd
=> mouse2rgtr: right and middle click on hzscale do the same as on the grid

ULX3S/scopeio/scopeio.vhd, library/scope/scopeio.vhd, library/scope/scopeio_mouse2rgtr.vhd, library/scope/scopeio_segment.vhd, library/video/videopkg.vhd
exposing axis_unit generic to be configurable for each board
=> mouse2rgtr fix for changed pallete ID's

library/scope/scopeio.vhd, library/scope/scopeio_capture1shot.vhd
+1 arithmetic is moved to 1shot block
=> scopeio: optimized alignment of 1 pixel to the grid,

ULX3S/scopeio/scopeio.vhd, library/scope/scopeio_usbmouse2daisy.vhd
and it can scope its own USB bus.
=> ULX3S toplevel and usbmouse2rgtr: it shows picture on monitor

ULX3S/scopeio/scopeio.vhd, library/scope/scopeio_mouse2rgtr.vhd, library/scope/scopeio_usbmouse2daisy.vhd, library/usbmouse/usb_enum_logitech_mouse_pack.vhd, library/usbmouse/usbhid_host.vhd
and some usb mouse changes just to keep it working
=> mouse2rgtr: fix snap to grid bug (tracking snap-to-grid state for each channel)

ULX3S/scopeio/scopeio.vhd, library/scope/scopeio.vhd, library/scope/scopeio_capture1shot.vhd
I can't get deflicker=true working again alfter latest changes on other places
=> capture1shot improved when deflicker=false

ULX3S/diamond/files.mk, ULX3S/diamond/ulx3s_12f_scope.ldf, ULX3S/scopeio/scopeio_top.vhd, ULX3S/tools/gridblink.sh, ULX3S/tools/hostmouse.py, ULX3S/tools/netgridblink.sh, library/scope/scopeio_palette.vhd, library/scope/scopeio_tds_1shot.vhd, library/scope/scopeio_udpipdaisy.vhd, library/scope/scopeio_video.vhd, library/scope/scopeiopkg.vhd, library/usb/usbcdc/usb_mii.vhd
=> follow up TDS and register changes

library/usb/usbhost/usbh_host_hid.vhd
Logitech UltraX keyboard now accepts set_address,
but this is not enough to make it work.
=> USB host cleanup: setup retries set_address data phase valid status reponse.

ULX3S/scopeio/scopeio_top.vhd
…erent connectors and cabling)
=> ULX3S toplevel: alias for easy swapping of AN108 GP/GN pins

library/usb/usb11_phy_vhdl/usb_rx_phy_emard.vhd
=> usb_rx_phy_emard.vhd: improve reliability, check stuffed bit

library/usb/usbhost/usbh_host_hid.vhd
if set_address fails, goto STATE_DETACHED
=> usbh_host_hid.vhd: hotplug reliability fix

library/usb/usbhost/usbh_host_hid.vhd
=> usbh_host_hid.vhd: SOF experimental code, device sends somehing and detaches

library/video/video.vhd
Some minor optimizations that helps to improve hardware resources and speed
=> External video sync minor optimization
